import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { PostsProvider } from "@/context/posts-context";
import { PropsWithChildren } from "react";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} antialiased`}>
        <PostsProvider>
          <Header />
          <main className="max-w-[1920px]">{children}</main>
        </PostsProvider>
      </body>
    </html>
  );
}
